@host = http://localhost:5000

### reset password (template)
@email = 
@refreshToken = 
POST {{host}}/reset-password/{{email}}/{{refreshToken}}
Content-Type: application/json

{
    "attempt_password": "1234",
    "confirm_password": "1234"
}


### [SUCCES] signup: user
POST {{host}}/signup
Content-Type: application/json

{
    "name": "quan",
    "email": "npquan2704@gmail.com",
    "password": "1234"
}

### forgot password (template)
POST {{host}}/forgot-password
Content-Type: application/json

{
    "email": "[EMAIL]"
}

### [FAILED] signin: old password
POST {{host}}/signin
Content-Type: application/json

{
    "email": "npquan2704@gmail.com",
    "password": "1234"
}

### [SUCCES] signin: new password
POST {{host}}/signin
Content-Type: application/json

{
    "email": "npquan2704@gmail.com",
    "password": "12345678"
}