@host = http://localhost:5000

### reset password (template)
@email = [EMAIL]
@token = [TOKEN]
POST {{host}}/reset-password/{{email}}/{{token}}
Content-Type: application/json

{
    "attempt_password": "12345678",
    "confirm_password": "12345678"
}


### [SUCCES] signup: user
POST {{host}}/signup
Content-Type: application/json

{
    "name": "quan",
    "email": "npquan2704@gmail.com",
    "password": "1234"
}

### forgot password
POST {{host}}/forgot-password
Content-Type: application/json

{
    "email": "npquan2704@gmail.com"
}

### reset password
POST http://localhost:5000/reset-password/npquan2704@gmail.com/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5wcXVhbjI3MDRAZ21haWwuY29tIiwiaWF0IjoxNzE3NzczNjM2LCJleHAiOjE3MTc3NzM2OTZ9.emRdOE6ULqB1zPez35vn_xyV_P3gmmEuURtFeYN4QHg
Content-Type: application/json

{
    "attempt_password": "12345678",
    "confirm_password": "12345678"
}

### [FAILED] signin: old password
POST {{host}}/signin
Content-Type: application/json

{
    "email": "npquan2704@gmail.com",
    "password": "1234"
}

### [SUCCES] signin: new password
POST {{host}}/signin
Content-Type: application/json

{
    "email": "npquan2704@gmail.com",
    "password": "12345678"
}