@host = http://localhost:5000

### [SUCCESS] server connection
GET {{host}}

### [FAILED] server connection: connect to invalid page
GET {{host}}/chat 

### [FAILED] signin: wrong email 
POST {{host}}/signin
Content-Type: application/json

{
    "email": "admin@gmail.com", 
    "password": "12345678"
}

### [FAILED] signin: wrong password
POST {{host}}/signin
Content-Type: application/json

{
    "email": "a@gmail.com",
    "password": "1234"
}

### [SUCCESS] signin: admin
POST {{host}}/signin
Content-Type: application/json

{
    "email": "a@gmail.com",
    "password": "12345678"
}

### [SUCCESS] signin: user
POST {{host}}/signin
Content-Type: application/json

{
    "email": "u@gmail.com",
    "password": "12345678"
}

### [SUCCESS] signup: admin
POST {{host}}/signup
Content-Type: application/json

{
    "name": "admin",
    "email": "a@gmail.com",
    "password": "12345678"
}

### [SUCESS] signup: user
POST {{host}}/signup
Content-Type: application/json

{
    "name": "user",
    "email": "u@gmail.com",
    "password": "12345678"
}

### [FAILED] signup: email is invalid
POST {{host}}/signup
Content-Type: application/json

{
    "email": "a@a",
    "password": "12345678"
}

### [USER] get profile 
GET {{host}}profile
Authorization: Bearer [TOKEN]

### [ADMIN] get all users
GET {{host}}/getall
Authorization: Bearer [TOKEN]

### sign out
POST {{host}}/signout

### reset password
@email = [EMAIL]
@token = [TOKEN]
POST {{host}}/reset-password/{{email}}/{{token}}
Content-Type: application/json

{
    "attempt_password": "12345678",
    "confirm_password": "12345678"
}